nintendo = Company.find_or_create_by(name: 'Nintendo')
nintendo.consoles.find_or_create_by(name: 'NES', release_year: 1983)
nintendo.consoles.find_or_create_by(name: 'Game Boy', release_year: 1989)
nintendo.consoles.find_or_create_by(name: 'SNES', release_year: 1990)
nintendo.consoles.find_or_create_by(name: 'N64', release_year: 1996)
nintendo.consoles.find_or_create_by(name: 'GameCube', release_year: 2001)
nintendo.consoles.find_or_create_by(name: 'Game Boy Advance', release_year: 2001)
nintendo.consoles.find_or_create_by(name: 'Nintendo DS', release_year: 2006)
nintendo.consoles.find_or_create_by(name: 'Wii', release_year: 2006)
nintendo.consoles.find_or_create_by(name: 'Nintendo 3DS', release_year: 2011)
nintendo.consoles.find_or_create_by(name: 'Wii U', release_year: 2012)
nintendo.consoles.find_or_create_by(name: 'Nintendo Switch', release_year: 2017)

sega = Company.find_or_create_by(name: 'Sega')
sega.consoles.find_or_create_by(name: 'Genesis', release_year: 1988)
sega.consoles.find_or_create_by(name: 'Game Gear', release_year: 1990)
sega.consoles.find_or_create_by(name: 'Sega Saturn', release_year: 1990)
sega.consoles.find_or_create_by(name: 'Dreamcast', release_year: 1998)

sony = Company.find_or_create_by(name: 'Sony')
sony.consoles.find_or_create_by(name: 'PlayStation', release_year: 1994)
sony.consoles.find_or_create_by(name: 'PlayStation 2', release_year: 2000)
sony.consoles.find_or_create_by(name: 'PlayStation Portable', release_year: 2004)
sony.consoles.find_or_create_by(name: 'PlayStation 3', release_year: 2006)
sony.consoles.find_or_create_by(name: 'PlayStation Vita', release_year: 2013)
sony.consoles.find_or_create_by(name: 'PlayStation 4', release_year: 2013)

microsoft = Company.find_or_create_by(name: 'Microsoft')
microsoft.consoles.find_or_create_by(name: 'Xbox', release_year: 2001)
microsoft.consoles.find_or_create_by(name: 'Xbox 360', release_year: 2005)
microsoft.consoles.find_or_create_by(name: 'Xbox One', release_year: 2013)
